title: The Road to Genius - Allison Bejeck 
author: Allison Bejeck
github_username: abejeck
description: My thoughts on industry trends, fundamental skills, and cybersecurity.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
baseurk:
url: https://abejeck.github.io


# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
#   - jekyll-remote-theme