title: The Road to Genius - Allison Bejeck 
author: Allison Bejeck
description: My thoughts on industry trends, fundamental skills, or cybersecurity.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
url: https://abejeck.github.io/